site_name: My Docs
theme:
  name: material
  features:
    - content.code.copy
    - content.tabs.link

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.betterem
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 
  - tables
  - footnotes
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.emoji
  - tables
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true





#   - pymdownx.highlight:
#       anchor_linenums: true
#       use_pygments: true
#       pygments_lang_class: true
# #      auto_title: true
#       linenums: true
#       linenums_style: pymdownx-inline
#       line_spans: __span



  - pymdownx.keys
  - pymdownx.smartsymbols


nav:
  - 前言: "index.md"
  - practical_skills:
      - markdown_tutorial: "practical_skills/markdown_tutorial.md"
      - git&github: "practical_skills/git_learning.md"
      - shell: "practical_skills/shell_learning.md"
      - vim: "practical_skills/vim_learning.md"

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Andy-xiaokang/my-mkdocs

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
