site_name: CS Route Docs
site_url: https://andy-xiaokang.github.io/my-mkdocs/
site_author: Andy-xiaokang

repo_name: my-mkdocs
repo_url: https://github.com/andy-xiaokang/my-mkdocs/

copyright: Copyright &copy; 2023-present <a href="https://github.com/andy-xiaokang" target="_blank" rel="noopener noreferrer">Andy-xiaokang</a>
theme:
  name: material

  font:
    text: Roboto
    # text: Inconsolata
    # text: Noto Serif Simplified Chinese
    # text: Lora 
    # text: PT Serif
    # text: EB Garamond

  features:
    - content.code.copy
    - content.tabs.link

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.betterem
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 
  - tables
  - footnotes
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.emoji
  - tables
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.keys
  - pymdownx.smartsymbols


nav:
  - CSDIY课程路线: "CSDIY_ROUTE.md"
  - 前言: "index.md"
  - MIT_missing&practical_skills:
      - markdown_tutorial: "MIT_missing&practical_skills/markdown_tutorial.md"
      - git&github: "MIT_missing&practical_skills/git_learning.md"
      - shell: "MIT_missing&practical_skills/shell_learning.md"
      - vim: "MIT_missing&practical_skills/vim_learning.md"
      - data_wrangling: "MIT_missing&practical_skills/data_wrangling.md"
      - command-line environment: "MIT_missing&practical_skills/Command_line_environment.md"
      - Version control(Git): "MIT_missing&practical_skills/Git.md"
      - Metaprogramming: "MIT_missing&practical_skills/metaprogramming.md"
      - Docker: "MIT_missing&practical_skills/docker.md"
  - CS50X:
      - week1: "CS50/week1.md"
      - week2: "CS50/week2.md"
      - week3: "CS50/week3.md"
      - week4: "CS50/week4.md"
      - week5: "CS50/week5.md"
  - CS50P:
      - week0: "CS50P/week0.md"
      - week1: "CS50P/week1.md"
      - week2: "CS50P/week2.md"
      - week3: "CS50P/week3.md"
      - week4: "CS50P/week4.md"
  - CS61A-2020-summer:
      - chapter1: "CS61A-2020-summer/chapter1.md"
      - chapter2: "CS61A-2020-summer/chapter2.md"
      - chapter4: "CS61A-2020-summer/chapter4.md"


extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Andy-xiaokang/my-mkdocs
    # - icon: fontawesome/solid/paper-plane
    #   link: mailto:x2177877404@gmail.com

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
