site_name: CSDIY Route Docs
site_url: https://andy-xiaokang.github.io/my-mkdocs/
site_author: Andy-xiaokang
repo_name: my-mkdocs
repo_url: https://github.com/andy-xiaokang/my-mkdocs/
copyright: Copyright &copy; 2023-05-present <a href="https://github.com/andy-xiaokang" target="_blank" rel="noopener noreferrer">Andy-xiaokang</a>

theme:
  name: material

  font:
    text: Roboto
    # text: Inconsolata
    # text: Noto Serif Simplified Chinese
    # text: Lora 
    # text: PT Serif
    # text: EB Garamond

  features:
    - content.code.copy
    - content.tabs.link

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.betterem
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 
  - tables
  - footnotes
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.emoji
  - tables
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.keys
  - pymdownx.smartsymbols


nav:
  - CSDIY课程路线: "index.md"
  - mkdocs markdown syntax: "mkdocs_markdownsyntax.md"
  - MITmissing&&practical skills:
      - markdown tutorial: "MIT_missing&practical_skills/markdown_tutorial.md"
      - git&github: "MIT_missing&practical_skills/git_learning.md"
      - shell: "MIT_missing&practical_skills/shell_learning.md"
      - vim: "MIT_missing&practical_skills/vim_learning.md"
      - data wrangling: "MIT_missing&practical_skills/data_wrangling.md"
      - command-line environment: "MIT_missing&practical_skills/Command_line_environment.md"
      - Version control(Git): "MIT_missing&practical_skills/Git.md"
      - Metaprogramming: "MIT_missing&practical_skills/metaprogramming.md"
      - Docker: "MIT_missing&practical_skills/docker.md"
  - CS50X:
      - week1: "CS50/week1.md"
      - week2: "CS50/week2.md"
      - week3: "CS50/week3.md"
      - week4: "CS50/week4.md"
      - week5: "CS50/week5.md"
  - CS50P:
      - week0: "CS50P/week0.md"
      - week1: "CS50P/week1.md"
      - week2: "CS50P/week2.md"
      - week3: "CS50P/week3.md"
      - week4: "CS50P/week4.md"
  - CS61A-2020-summer:
      - chapter1: "CS61A-2020-summer/chapter1.md"
      - chapter2: "CS61A-2020-summer/chapter2.md"
      - chapter3: "CS61A-2020-summer/chapter3.md"
      - chapter4: "CS61A-2020-summer/chapter4.md"
  - CS61B-2018-sp:
      - Introduction_to_java: "CS61B-2018-spring/Introduction_to_java.md"
      - Lists: "CS61B-2018-spring/Lists.md"
      - Testing: "CS61B-2018-spring/Testing.md"
      - Inheritance&Implements: "CS61B-2018-spring/inheritance&implements.md"
      - Generics && Autoboxing: "CS61B-2018-spring/generics&autoboxing.md"
      - Exceptions, Iterators, Iterables, Object Methods: "CS61B-2018-spring/exceptions&iterators&iterables&objectmethods.md"
      - Packages And Access Control: "CS61B-2018-spring/packages&accesscontrol.md"
      - Efficient Programming: "CS61B-2018-spring/efficient_programming.md"
      - Disjoint Sets: "CS61B-2018-spring/disjoint_sets.md"
      - ADTs: "CS61B-2018-spring/ADTs.md"
      - Balanced Trees: "CS61B-2018-spring/balanced_trees.md"
      - Hashing: "CS61B-2018-spring/hashing.md"
      
  - Computer-English:
      - Unit1: "Computer_English/Unit1.md" 
      - Unit2: "Computer_English/Unit2.md" 
      - Unit3: "Computer_English/Unit3.md" 
      - Unit4: "Computer_English/Unit4.md" 
      - Unit5: "Computer_English/Unit5.md" 
      - Unit6: "Computer_English/Unit6.md" 
      - Unit7: "Computer_English/Unit7.md" 
      - Unit8: "Computer_English/Unit8.md" 
      - Unit9: "Computer_English/Unit9.md" 
      - Unit10: "Computer_English/Unit10.md" 
      - Unit11: "Computer_English/Unit11.md" 
      - Unit12: "Computer_English/Unit12.md" 
  - ETC: 
      - mactips: "etc/mactips.md"
      - bugs&questions: "etc/bugs.md"
      - terminology: "etc/terminology.md"
      - prose: "etc/prose.md"

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Andy-xiaokang/my-mkdocs
    - icon: fontawesome/solid/paper-plane
      link: mailto:x2177877404@gmail.com

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
